-- Status lookup v6: ID order 8 karakter tanpa suffix WhatsApp.

create table if not exists public.status_lookup_attempts (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  attempted_at timestamptz not null default now()
);
create index if not exists status_lookup_attempts_rate_idx
  on public.status_lookup_attempts(visitor_id, attempted_at desc);
alter table public.status_lookup_attempts enable row level security;

create or replace function public.get_order_public_by_code(p_order_code text, p_visitor_id uuid)
returns table(
  order_code text,
  status text,
  items jsonb,
  subtotal_idr integer,
  discount_percent integer,
  total_idr integer,
  promo_code text,
  created_at timestamptz,
  admin_note text,
  notes text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_code text := upper(trim(coalesce(p_order_code, '')));
begin
  if p_visitor_id is null then raise exception 'VISITOR_REQUIRED'; end if;
  if normalized_code !~ '^IMZ-[A-Z0-9]{8}$' then raise exception 'INVALID_ORDER_CODE'; end if;
  if (select count(*) from public.status_lookup_attempts
      where visitor_id = p_visitor_id and attempted_at > now() - interval '1 minute') >= 20 then
    raise exception 'RATE_LIMITED';
  end if;

  insert into public.status_lookup_attempts(visitor_id) values (p_visitor_id);
  return query
    select o.order_code, o.status, o.items, o.subtotal_idr, o.discount_percent,
           o.total_idr, o.promo_code, o.created_at, o.admin_note, o.notes
      from public.orders o
     where o.order_code = normalized_code
     order by o.created_at desc
     limit 1;
end;
$$;

grant execute on function public.get_order_public_by_code(text,uuid) to anon, authenticated;
