-- Secure checkout foundation: reservations, payment reports, restock demand and funnel analytics.
-- Apply once in Supabase SQL editor before deploying the matching frontend.

create extension if not exists pgcrypto;

alter table public.orders add column if not exists reservation_expires_at timestamptz;
alter table public.orders add column if not exists payment_reported_at timestamptz;
alter table public.orders add column if not exists payment_reference text;
alter table public.orders add column if not exists verification_status text not null default 'unverified';
alter table public.orders add column if not exists inventory_committed_at timestamptz;
alter table public.testimonials add column if not exists product_name text;
alter table public.testimonials add column if not exists customer_name text;
alter table public.testimonials add column if not exists is_verified boolean not null default false;
alter table public.testimonials add column if not exists purchased_at timestamptz;

create unique index if not exists orders_order_code_secure_unique on public.orders(order_code)
  where order_code ~ '^IMZ-[A-HJ-NP-Z2-9]{8,10}$';
create unique index if not exists orders_payment_reference_unique on public.orders(payment_reference)
  where payment_reference is not null and payment_reference <> 'FREE';
create index if not exists orders_reservation_expiry_idx on public.orders(reservation_expires_at)
  where status = 'pending_payment';

create table if not exists public.funnel_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  session_id uuid not null,
  event_name text not null check (event_name in (
    'view_product','select_variant','add_to_cart','buy_now','begin_checkout',
    'apply_promo','qris_opened','payment_reported','order_completed','restock_request'
  )),
  path text,
  product_id uuid,
  variant_id uuid,
  order_code text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists funnel_events_created_idx on public.funnel_events(created_at desc);
create index if not exists funnel_events_session_idx on public.funnel_events(session_id, created_at);

create table if not exists public.restock_requests (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  product_id uuid references public.products(id) on delete cascade,
  variant_id uuid references public.product_variants(id) on delete cascade,
  customer_whatsapp text not null,
  created_at timestamptz not null default now(),
  notified_at timestamptz,
  unique(visitor_id, variant_id)
);

create table if not exists public.status_lookup_attempts (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  attempted_at timestamptz not null default now()
);
create index if not exists status_lookup_attempts_rate_idx
  on public.status_lookup_attempts(visitor_id, attempted_at desc);
alter table public.status_lookup_attempts enable row level security;

alter table public.funnel_events enable row level security;
alter table public.restock_requests enable row level security;

drop policy if exists "anon insert funnel events" on public.funnel_events;
create policy "anon insert funnel events" on public.funnel_events for insert to anon, authenticated with check (true);
drop policy if exists "anon create restock request" on public.restock_requests;
create policy "anon create restock request" on public.restock_requests for insert to anon, authenticated with check (true);
drop policy if exists "admin read restock requests" on public.restock_requests;
create policy "admin read restock requests" on public.restock_requests for select to authenticated
  using (exists(select 1 from public.admin_users where user_id = auth.uid()));
drop policy if exists "admin update restock requests" on public.restock_requests;
create policy "admin update restock requests" on public.restock_requests for update to authenticated
  using (exists(select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists(select 1 from public.admin_users where user_id = auth.uid()));

create or replace function public.expire_order_reservations()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  expired_order record;
  released integer := 0;
begin
  for expired_order in
    select id from public.orders
    where status = 'pending_payment'
      and reservation_expires_at is not null
      and reservation_expires_at <= now()
    for update skip locked
  loop
    update public.product_variants pv
       set stock = pv.stock + oi.qty,
           updated_at = now()
      from public.order_items oi
     where oi.order_id = expired_order.id and oi.variant_id = pv.id;

    update public.orders
       set status = 'expired', verification_status = 'expired'
     where id = expired_order.id;

    released := released + 1;
  end loop;
  return released;
end;
$$;

create or replace function public.sync_order_inventory_and_verification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status = 'pending_payment' and new.status = 'cancelled' then
    update public.product_variants pv set stock = pv.stock + oi.qty, updated_at = now()
      from public.order_items oi where oi.order_id = new.id and oi.variant_id = pv.id;
    new.verification_status := 'rejected';
  elsif new.status in ('processing', 'done') then
    new.verification_status := 'verified';
  end if;

  if old.inventory_committed_at is null and new.status in ('processing', 'done') then
    update public.product_variants pv set sold_count = coalesce(pv.sold_count, 0) + oi.qty, updated_at = now()
      from public.order_items oi where oi.order_id = new.id and oi.variant_id = pv.id;
    new.inventory_committed_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists orders_inventory_verification_trigger on public.orders;
create trigger orders_inventory_verification_trigger
before update of status on public.orders
for each row execute function public.sync_order_inventory_and_verification();

create or replace function public.create_pending_order_reservation(
  p_visitor_id uuid,
  p_order_code text,
  p_items jsonb,
  p_promo_code text default null,
  p_customer_whatsapp text default null,
  p_notes text default null,
  p_reservation_minutes integer default 30
)
returns table(order_code text, status text, reservation_expires_at timestamptz, total_idr integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  next_order_id uuid := gen_random_uuid();
  item jsonb;
  variant_row record;
  requested_qty integer;
  line_price integer;
  canonical_subtotal integer := 0;
  promo_percent integer := 0;
  canonical_total integer;
  expiry timestamptz := now() + make_interval(mins => greatest(5, least(coalesce(p_reservation_minutes, 30), 60)));
  normalized_phone text := regexp_replace(coalesce(p_customer_whatsapp, ''), '\D', '', 'g');
begin
  perform public.expire_order_reservations();

  if p_visitor_id is null then raise exception 'VISITOR_REQUIRED'; end if;
  if p_order_code !~ '^IMZ-[A-HJ-NP-Z2-9]{8,10}$' then raise exception 'INVALID_ORDER_CODE'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'EMPTY_CART'; end if;
  if length(normalized_phone) < 10 or length(normalized_phone) > 15 then raise exception 'INVALID_WHATSAPP'; end if;

  if (select count(*) from public.orders where visitor_id = p_visitor_id and created_at > now() - interval '1 minute') >= 5 then
    raise exception 'RATE_LIMITED';
  end if;

  insert into public.orders(
    id, visitor_id, items, subtotal_idr, discount_percent, total_idr, status, created_at,
    order_code, customer_whatsapp, notes, reservation_expires_at, verification_status
  ) values (
    next_order_id, p_visitor_id, '[]'::jsonb, 0, 0, 0, 'pending_payment', now(),
    p_order_code, normalized_phone, nullif(trim(coalesce(p_notes, '')), ''), expiry, 'unverified'
  );

  for item in select * from jsonb_array_elements(p_items)
  loop
    requested_qty := greatest(1, least(coalesce((item->>'qty')::integer, 1), 99));
    select pv.*, p.name as product_name, p.icon_url as product_icon_url, p.is_active as product_active
      into variant_row
      from public.product_variants pv
      join public.products p on p.id = pv.product_id
     where pv.id = (item->>'variant_id')::uuid
     for update of pv;

    if not found or variant_row.is_active is false or variant_row.product_active is false then raise exception 'VARIANT_UNAVAILABLE'; end if;
    if variant_row.stock < requested_qty then raise exception 'INSUFFICIENT_STOCK'; end if;

    select coalesce(round(variant_row.price_idr * (1 - fs.discount_percent::numeric / 100))::integer, variant_row.price_idr)
      into line_price
      from (select 1) seed
      left join lateral (
        select discount_percent from public.flash_sales
        where variant_id = variant_row.id and is_active = true and starts_at <= now() and ends_at > now()
        order by discount_percent desc limit 1
      ) fs on true;

    canonical_subtotal := canonical_subtotal + line_price * requested_qty;

    insert into public.order_items(
      id, order_id, variant_id, product_id, product_name, variant_name, duration_label,
      price_idr, qty, product_icon_url, description, guarantee_text, requires_buyer_email
    ) values (
      gen_random_uuid(), next_order_id, variant_row.id, variant_row.product_id, variant_row.product_name,
      variant_row.name, variant_row.duration_label, line_price, requested_qty, variant_row.product_icon_url,
      variant_row.description, variant_row.guarantee_text, variant_row.requires_buyer_email
    );

    update public.product_variants set stock = stock - requested_qty, updated_at = now() where id = variant_row.id;
  end loop;

  if nullif(trim(coalesce(p_promo_code, '')), '') is not null then
    select percent into promo_percent from public.promo_codes
     where code = upper(trim(p_promo_code)) and is_active = true
       and (expired_at is null or expired_at > now())
       and (max_uses is null or used_count < max_uses)
       and not exists (
         select 1 from public.promo_claims pc
         where pc.visitor_id = p_visitor_id and pc.code = upper(trim(p_promo_code))
       )
     for update;
    promo_percent := coalesce(promo_percent, 0);
  end if;

  canonical_total := greatest(0, canonical_subtotal - round(canonical_subtotal * promo_percent::numeric / 100)::integer);

  update public.orders o set
    items = payload.items,
    subtotal_idr = canonical_subtotal,
    discount_percent = promo_percent,
    total_idr = canonical_total,
    promo_code = case when promo_percent > 0 then upper(trim(p_promo_code)) else null end
  from (
    select coalesce(jsonb_agg(to_jsonb(oi) - 'id' - 'order_id' - 'created_at'), '[]'::jsonb) as items
    from public.order_items oi where oi.order_id = next_order_id
  ) payload
  where o.id = next_order_id;

  return query select p_order_code, 'pending_payment'::text, expiry, canonical_total;
exception when others then
  delete from public.order_items where order_id = next_order_id;
  delete from public.orders where id = next_order_id;
  raise;
end;
$$;

create or replace function public.report_order_payment(
  p_order_code text,
  p_phone_suffix text,
  p_payment_reference text default null,
  p_payment_proof_url text default null
)
returns table(order_code text, status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.orders%rowtype;
  suffix text := regexp_replace(coalesce(p_phone_suffix, ''), '\D', '', 'g');
begin
  perform public.expire_order_reservations();
  select * into target from public.orders where orders.order_code = upper(trim(p_order_code)) for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if right(regexp_replace(coalesce(target.customer_whatsapp, ''), '\D', '', 'g'), 4) <> right(suffix, 4) then raise exception 'ORDER_VERIFICATION_FAILED'; end if;
  if target.status <> 'pending_payment' or target.reservation_expires_at <= now() then raise exception 'RESERVATION_EXPIRED'; end if;
  if nullif(trim(coalesce(p_payment_reference, '')), '') is null and nullif(trim(coalesce(p_payment_proof_url, '')), '') is null then
    raise exception 'PAYMENT_EVIDENCE_REQUIRED';
  end if;

  update public.orders set
    status = 'paid_reported', payment_reported_at = now(), verification_status = 'pending_review',
    payment_reference = nullif(trim(coalesce(p_payment_reference, '')), ''),
    payment_proof_url = nullif(trim(coalesce(p_payment_proof_url, '')), '')
  where id = target.id;

  if target.promo_code is not null then
    update public.promo_codes set used_count = coalesce(used_count, 0) + 1 where code = target.promo_code;
    insert into public.promo_claims(visitor_id, code) values (target.visitor_id, target.promo_code);
  end if;
  return query select target.order_code, 'paid_reported'::text;
end;
$$;

create or replace function public.get_order_public_secure(p_order_code text, p_phone_suffix text, p_visitor_id uuid)
returns table(
  order_code text, status text, items jsonb, subtotal_idr integer, discount_percent integer,
  total_idr integer, promo_code text, created_at timestamptz, admin_note text, notes text,
  reservation_expires_at timestamptz, verification_status text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_visitor_id is null then raise exception 'VISITOR_REQUIRED'; end if;
  if (select count(*) from public.status_lookup_attempts
      where visitor_id = p_visitor_id and attempted_at > now() - interval '1 minute') >= 20 then
    raise exception 'RATE_LIMITED';
  end if;
  insert into public.status_lookup_attempts(visitor_id) values (p_visitor_id);
  perform public.expire_order_reservations();
  return query
  select o.order_code, o.status, o.items, o.subtotal_idr, o.discount_percent, o.total_idr,
         o.promo_code, o.created_at, o.admin_note, o.notes, o.reservation_expires_at, o.verification_status
    from public.orders o
   where o.order_code = upper(trim(p_order_code))
     and right(regexp_replace(coalesce(o.customer_whatsapp, ''), '\D', '', 'g'), 4)
         = right(regexp_replace(coalesce(p_phone_suffix, ''), '\D', '', 'g'), 4)
     and length(regexp_replace(coalesce(p_phone_suffix, ''), '\D', '', 'g')) >= 4;
end;
$$;

create or replace function public.get_funnel_summary(p_days integer default 7)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  allowed boolean;
  result jsonb;
begin
  select exists(select 1 from public.admin_users where user_id = auth.uid()) into allowed;
  if not allowed then raise exception 'ADMIN_REQUIRED'; end if;

  with names(event_name, sort_order) as (values
    ('view_product', 1), ('add_to_cart', 2), ('begin_checkout', 3),
    ('qris_opened', 4), ('payment_reported', 5), ('order_completed', 6)
  ), counts as (
    select n.event_name, n.sort_order, count(distinct f.session_id)::integer as sessions
    from names n left join public.funnel_events f
      on f.event_name = n.event_name
     and f.created_at >= now() - make_interval(days => greatest(1, least(coalesce(p_days, 7), 90)))
    group by n.event_name, n.sort_order
  ), rates as (
    select event_name, sort_order, sessions,
      case
        when lag(sessions) over (order by sort_order) is null then 100
        when lag(sessions) over (order by sort_order) = 0 then 0
        else round(sessions::numeric * 100 / lag(sessions) over (order by sort_order), 1)
      end as rate_from_previous
    from counts
  )
  select jsonb_build_object(
    'days', greatest(1, least(coalesce(p_days, 7), 90)),
    'steps', jsonb_agg(jsonb_build_object(
      'event_name', event_name,
      'sessions', sessions,
      'rate_from_previous', rate_from_previous
    ) order by sort_order)
  ) into result from rates;
  return result;
end;
$$;

-- Tutup endpoint lookup lama yang hanya membutuhkan ID order.
do $$
declare candidate regprocedure;
begin
  for candidate in
    select p.oid::regprocedure from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'get_order_public'
  loop
    execute format('revoke execute on function %s from anon, authenticated', candidate);
  end loop;
end $$;

grant execute on function public.expire_order_reservations() to anon, authenticated;
grant execute on function public.create_pending_order_reservation(uuid,text,jsonb,text,text,text,integer) to anon, authenticated;
grant execute on function public.report_order_payment(text,text,text,text) to anon, authenticated;
grant execute on function public.get_order_public_secure(text,text,uuid) to anon, authenticated;
grant execute on function public.get_funnel_summary(integer) to authenticated;
grant insert on public.funnel_events to anon, authenticated;
grant insert on public.restock_requests to anon, authenticated;
